Repository dnd-side-project/dnd-9th-5-backend, pull requests merged in 2023-08, with the labels that each got.

#3 refactor: poseTalk API
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/dndoz/PosePicker/Config/SwaggerConfig.java
  src/main/java/com/dndoz/PosePicker/Controller/PoseController.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseWord.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseTalkResponse.java
  src/main/java/com/dndoz/PosePicker/Global/entity/BaseEntity.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseRepository.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
  src/main/resources/application.properties
Labels: refactor

#4 feat: 포즈 상세조회 API
  build.gradle
  src/main/java/com/dndoz/PosePicker/Controller/PoseInfoController.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseInfoResponse.java
  src/main/java/com/dndoz/PosePicker/PosePickerApplication.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseInfoRepository.java
  src/main/java/com/dndoz/PosePicker/Service/PoseInfoService.java
Labels: feat

#7 fix: Pose Info 엔티티 변경
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseInfoRepository.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
Labels: fix, refactor

#8 feat: 포즈 필터링 api
  src/main/java/com/dndoz/PosePicker/Controller/PoseController.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseTag.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseFeedResponse.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseInfoResponse.java
  src/main/java/com/dndoz/PosePicker/Global/error/ErrorResponse.java
  src/main/java/com/dndoz/PosePicker/Global/error/GlobalExceptionHandler.java
  src/main/java/com/dndoz/PosePicker/Global/error/exception/BusinessException.java
  src/main/java/com/dndoz/PosePicker/Global/error/exception/EntityNotFoundException.java
  src/main/java/com/dndoz/PosePicker/Global/error/exception/ErrorCode.java
  src/main/java/com/dndoz/PosePicker/Global/error/exception/InvalidValueException.java
  src/main/java/com/dndoz/PosePicker/Global/status/StatusCode.java
  src/main/java/com/dndoz/PosePicker/Global/status/StatusResponse.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseInfoRepository.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseTagAttributeRepository.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
Labels: feat, fix

#9 feat: 카카오 로그인 API 및 jwt 토큰 발급
  build.gradle
  src/main/java/com/dndoz/PosePicker/Auth/AuthTokens.java
  src/main/java/com/dndoz/PosePicker/Auth/AuthTokensGenerator.java
  src/main/java/com/dndoz/PosePicker/Auth/JwtTokenProvider.java
  src/main/java/com/dndoz/PosePicker/Controller/UserController.java
  src/main/java/com/dndoz/PosePicker/Domain/User.java
  src/main/java/com/dndoz/PosePicker/Dto/LoginResponse.java
  src/main/java/com/dndoz/PosePicker/Repository/UserRepository.java
  src/main/java/com/dndoz/PosePicker/Service/UserService.java
Labels: feat

#10 fix: 포즈 필터링 정확도 개선
  build.gradle
  src/main/java/com/dndoz/PosePicker/Config/QuerydslConfig.java
  src/main/java/com/dndoz/PosePicker/Controller/PoseController.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfoWithAttributes.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseFeedRequest.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseInfoResponse.java
  src/main/java/com/dndoz/PosePicker/Global/error/GlobalExceptionHandler.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepository.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryCustom.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryImpl.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseInfoRepository.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
Labels: fix
