Repository dnd-side-project/dnd-9th-5-backend, pull requests merged in 2023-10, with the labels that each got.

#11 fix: 포즈 필터링 중복 데이터 방지
  src/main/java/com/dndoz/PosePicker/Dto/PoseFeedRequest.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryCustom.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryImpl.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
Labels: feat, fix

#12 feat: 북마크 API
  src/main/java/com/dndoz/PosePicker/Controller/BookmarkController.java
  src/main/java/com/dndoz/PosePicker/Domain/Bookmark.java
  src/main/java/com/dndoz/PosePicker/Dto/BookmarkRequest.java
  src/main/java/com/dndoz/PosePicker/Repository/BookmarkRepository.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseInfoRepository.java
  src/main/java/com/dndoz/PosePicker/Service/BookmarkService.java
Labels: feat

#13 fix : 포즈 태그 정제
  src/main/java/com/dndoz/PosePicker/Repository/PoseTagAttributeRepository.java
Labels: fix
