Repository dnd-side-project/dnd-9th-5-backend, pull requests merged in 2024-01, with the labels that each got.

#15 feat: 소셜로그인(kakao, apple) API
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/com/dndoz/PosePicker/Auth/AuthTokensGenerator.java
  src/main/java/com/dndoz/PosePicker/Auth/JwtTokenProvider.java
  src/main/java/com/dndoz/PosePicker/Auth/PPJwtTokenProvider.java
  src/main/java/com/dndoz/PosePicker/Controller/UserController.java
  src/main/java/com/dndoz/PosePicker/Domain/User.java
  src/main/java/com/dndoz/PosePicker/Dto/KakaoLoginRequest.java
  src/main/java/com/dndoz/PosePicker/Dto/PPTokenResponse.java
  src/main/java/com/dndoz/PosePicker/Service/AppleService.java
  src/main/java/com/dndoz/PosePicker/Service/KakaoService.java
Labels: feat, fix, chore

#16 fix: 북마크 및 포즈피드 수정 API
  build.gradle
  src/main/java/com/dndoz/PosePicker/Auth/JwtTokenProvider.java
  src/main/java/com/dndoz/PosePicker/Controller/BookmarkController.java
  src/main/java/com/dndoz/PosePicker/Controller/PoseController.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Dto/BookmarkRequest.java
  src/main/java/com/dndoz/PosePicker/Dto/BookmarkResponse.java
  src/main/java/com/dndoz/PosePicker/Repository/BookmarkRepository.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryCustom.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryImpl.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseInfoRepository.java
  src/main/java/com/dndoz/PosePicker/Service/BookmarkService.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
Labels: feat, fix

#17 feat: 어드민 포즈 정보 / 포즈 등록 폼
  build.gradle
  src/main/java/com/dndoz/PosePicker/Controller/AdminController.java
  src/main/java/com/dndoz/PosePicker/Controller/ViewController.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseTag.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseTagAttribute.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseUpdateRequest.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseUploadRequest.java
  src/main/java/com/dndoz/PosePicker/Global/entity/BaseEntity.java
  src/main/java/com/dndoz/PosePicker/PosePickerApplication.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseTagAttributeRepository.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseTagRepository.java
  src/main/java/com/dndoz/PosePicker/Service/AdminService.java
  src/main/resources/templates/details.html
  src/main/resources/templates/forms.html
  src/main/resources/templates/tables.html
Labels: feat

#20 fix: 포즈피드 태그 요청에 따른 응답 처리
  build.gradle
  src/main/java/com/dndoz/PosePicker/Config/AwsS3Config.java
  src/main/java/com/dndoz/PosePicker/Domain/PoseInfo.java
  src/main/java/com/dndoz/PosePicker/Dto/PoseFeedRequest.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryCustom.java
  src/main/java/com/dndoz/PosePicker/Repository/PoseFilterRepositoryImpl.java
  src/main/java/com/dndoz/PosePicker/Service/PoseService.java
Labels: fix, chore
